# spring.profiles.active=dev,test,custom
#spring.application.name=example

spring:
  #  profiles:
  #    active: dev,test,custom
  application:
    name: example
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect